/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.crm_cust_info', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.crm_cust_info;

CREATE TABLE raw_data_layer.crm_cust_info(
cst_id INT, -- ID DO CONSUMIDOR
cst_key NVARCHAR(50), -- CHAVE DO CONSUMIDOR
cst_firstname NVARCHAR(50), -- PRIMEIRO NOME DO CONSUMIDOR
cst_lastname NVARCHAR(50), -- ULTIMO NOME DO CONSUMIDOR
cst_marital_status NVARCHAR(50), -- STATUS DE CASAMENTO DO CONSUMIDOR
cst_gender NVARCHAR(50), -- GEENERO DO CONSUMIDOR
cst_create_date DATE -- DATA DE CRIACAO DO CONSUMIDOR NO SISTEMA
);

/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.prd_info', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.prd_info;

CREATE TABLE raw_data_layer.prd_info(
prd_id INT, -- ID DO PRODUTO
prd_key NVARCHAR(50), -- CHAVE DO PRODUTO
prd_name NVARCHAR(50), -- NOME DO PRODUTO
prd_cost INT, -- CUSTO DO PRODUTO
prd_line NVARCHAR(50), -- LINHA DE PRODUCAO DO PRODUTO
prd_start_dt DATE, -- DATA DE INICIO DA PRODUCAO DO PRODUTO
prd_end_dt DATE -- FIM DA PRODUCAO DO PRODUTO
);

/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.sales_details', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.sales_details;

CREATE TABLE raw_data_layer.sales_details(
sls_ord_num NVARCHAR(50), -- NUMERO DA VENDA
sls_prod_key NVARCHAR(50), -- CHAVE DA VENDA
sls_cust_id INT, -- ID DO VENDEDOR
sls_order_dt INT, -- DATA DE COMPRA
sls_ship_dt INT, -- DATA DE ENVIO
sls_due_dt DATE, -- DATA PREVISTA DE ENTREGA
sls_sales INT, -- VALOR TOTAL DA VENDA
sls_quantity INT, -- QUANTIDADE DE PRODUTOS VENDIDOS
sls_price DECIMAL, -- VALOR UNITARIO DOS PRODUTOS DA VENDA
);

/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.cust_az12', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.cust_az12;

CREATE TABLE raw_data_layer.cust_az12(
cid NVARCHAR(50), -- ID DO USUARIO/CONSUMIDOR
bdate DATE, -- DATA DE NASCIMENTO
gen NVARCHAR(50), -- GENERO USUARIO/CONSUMIDOR
);

/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.loc_a101', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.loc_a101;

CREATE TABLE raw_data_layer.loc_a101(
cid NVARCHAR(50), -- ID DO USUARIO/CONSUMIDOR
cntry NVARCHAR(50), -- PAIS DE ORIGEM DO USUARIO/CONSUMIDOR
);

/* VERIFICA SE JA EXISTE A TABELA NA DATABASE 
SE EXISTIR ELE DELETA ANTES DE CRIA-LA DE NOVO */
IF OBJECT_ID ('raw_data_layer.px_cat_g1v2', 'U') IS NOT NULL
	DROP TABLE raw_data_layer.px_cat_g1v2;

CREATE TABLE raw_data_layer.px_cat_g1v2(
id NVARCHAR(50), -- ID DO PRODUTO
cat NVARCHAR(50), -- CATEGORIA
subcat NVARCHAR(50), -- SUBCATEGORIA
maintenance NVARCHAR(5), -- "OFERECE MANUTENCAO??"
);
